# Generated by Django 5.0.2 on 2024-12-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_customuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='GCCoins',
            field=models.IntegerField(default=0),
        ),
    ]
