# Generated by Django 5.0.2 on 2024-12-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_customuser_gccoins'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='GCCoins',
            new_name='gc_coins',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='customuser',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
