# Generated by Django 5.0.2 on 2025-02-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0007_alter_customuser_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.TextField(default='Enter your address'),
        ),
    ]
