# Generated by Django 5.0.2 on 2025-01-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecoaware', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_submission',
            name='image',
            field=models.ImageField(blank=True, upload_to='task_submissions/'),
        ),
        migrations.AddField(
            model_name='task_submission',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
