# Generated by Django 5.0.2 on 2025-02-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecoaware', '0002_task_submission_image_task_submission_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('filename', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
