# Generated by Django 5.0.2 on 2025-02-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecoaware', '0003_mediametadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaForge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(blank=True, max_length=30)),
                ('task_description', models.TextField()),
                ('task_video', models.FileField(blank=True, upload_to='Ideaforge_submissions/')),
            ],
        ),
    ]
