# Generated by Django 5.0.2 on 2025-02-26 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCS', '0006_remove_cartitem_cart_cartitem_user_delete_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered')], default='Ordered', max_length=20),
        ),
    ]
