# Generated by Django 5.0.2 on 2025-02-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GCS', '0007_orders_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
